apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-speed-reader
  labels:
    app: react-speed-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-speed-reader
  template:
    metadata:
      labels:
        app: react-speed-reader
    spec:
      containers:
        - name: react-speed-reader
          image: 396608810227.dkr.ecr.ap-south-1.amazonaws.com/react-image-registry:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-speed-reader
spec:
  selector:
    app: react-speed-reader
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
